version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"samples/build.gradle\" }}-\
                {{ checksum  \"webrtc-video-effector/build.gradle\" }}"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"samples/build.gradle\" }}-\
                {{ checksum  \"webrtc-video-effector/build.gradle\" }}"

      - run:
          name: Run lint
          command: ./gradlew lint
      - run:
          name: Build release
          command: ./gradlew --debug assembleRelease
      - run:
          name: Build debug
          command: ./gradlew --debug assembleDebug

      - store_artifacts:
          path: samples/build/outputs
          destination: outputs
      - store_artifacts:
          path: samples/build/reports
          destination: samples-reports
      - store_artifacts:
          path: webrtc-video-effector/build/reports
          destination: effector-reports
